// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyuvlruokmgpxogetybp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5dXZscnVva21ncHhvZ2V0eWJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjI4OTAsImV4cCI6MjA2ODgzODg5MH0.OHkhNNDVEr-ZiEkyefS-dFCc-8PodNNptz7QIIW0dQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});